---

- block:
  - name: Determine if VM has CDROM
    command: grep -q cdrom /etc/libvirt/qemu/{{ inventory_hostname }}.xml
    # AB: don't use virsh dumpxml since it shows the current
    # state of the VM. So, if someone already removed the
    # cdrom in the definition file with virt-xml, it still
    # shows up in the actual state. For the cdrom not to
    # show up in dumpxml, the VM must be stopped (and
    # possibly started again).
    #shell: virsh dumpxml {{ inventory_hostname }} | grep cdrom
    register: has_cdrom_info
    changed_when: false
    failed_when: false

  - name: Remove CDROM from VM
    command: virt-xml {{ inventory_hostname }} --remove-device --disk device=cdrom
    when: has_cdrom_info.rc == 0

  become: True
  delegate_to: localhost
