---

# AB: the name of the VG used as the pool for KVM volumes.
# See TODO in cleanupvm.
#makevolume_vg: centos
makevolume_vg: fedora

# AB: the size of the system disk volume. Default is set to
# 4 GiB. For value specification see section "NOTES" of
# virsh(1). So g == G == GiB.
makevolume_size: 4g
