---

- name: XFS dump partitions
  block:

  - name: Dump the root partition
    command: xfsdump -L '' -M '' -f /mnt/data/rootfs /
    args:
      creates: /mnt/data/rootfs

  - name: Dump the boot partition
    command: xfsdump -L '' -M '' -f /mnt/data/bootfs /boot
    args:
      creates: /mnt/data/bootfs

  become: True
