---

# AB: TODO: figure out how we can set this parameter
# dependent on the OS distribution type. For example with:
# ansible -i localhost, localhost \
#   -m setup -a 'filter=ansible_distribution'
# Or, otherwise figure out how we can automatically find the
# VG (Volume Group) to use, e.g. centos or fedora.
# AB: the name of the VG used as the pool for KVM volumes.
#installsoftware_vg: centos
installsoftware_vg: fedora

# AB: the PV that maps onto the VG.
installsoftware_dev: /dev/nvme0n1p3
