---

- name: Attach template disk to domain if not attached
  block:
  - name: Verify if template disk is attached to domain
    shell: virsh domblklist {{ inventory_hostname }} | grep -q /dev/{{ attachtemplatedisk }}/t{{ inventory_hostname }}
    register: _block_list_info
    changed_when: false
    failed_when: false

  - name: Attach template disk to domain
    command: virsh attach-disk {{ inventory_hostname }} /dev/{{ attachtemplatedisk }}/t{{ inventory_hostname }} vdc
    when: _block_list_info.rc == 1
  become: true
  delegate_to: localhost
