---

- name: Attach template disk to domain if not attached
  block:

  - name: Verify if template disk is attached to domain
    shell: virsh domblklist {{ inventory_hostname }} | grep -q /dev/os/tpl
    register: block_list_info
    changed_when: False
    failed_when: False

  - name: Attach template disk to domain
    command: virsh attach-disk {{ inventory_hostname }} /dev/os/tpl vdc
    when: block_list_info.rc == 1

  become: True
  delegate_to: localhost
